# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI - Dev to Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Configure Git with token
      run: |
        git config --global user.email "MortallicaXxX@hotmail.com"
        git config --global user.name "MortallicaXxX"
        git config --global credential.helper store
        echo "https://github.com:${{ secrets.PUBLISH_TOKEN }}" > ~/.git-credentials
        chmod 0600 ~/.git-credentials

    - name: Fetch branch information from remote
      run: git fetch

    - name: Create test branch locally
      run: git checkout -b test origin/test

    - name: Merge dev into test
      run: git merge --no-ff --allow-unrelated-histories -X ours dev

    - name: Push changes to test branch
      run: git push origin test

    - name: Run Node.js CI - Test to Production workflow
      run: lithium-framework/huid/.github/workflows/node.test.yml@test
